FROM mcr.microsoft.com/dotnet/core/sdk as sdkimage
WORKDIR /app
COPY . .
RUN dotnet restore
RUN dotnet publish DockerizeExampleProject.csproj -c Release -o out
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=sdkimage /app/out .
ENV ASPNETCORE_URLS="http://*:1453"
ENTRYPOINT ["dotnet", "DockerizeExampleProject.dll"]
